### ISSUE TITLE
42 Bangkok Forum app

### ISSUE THREAD

**Issue by hazamashoken** [42-Bangkok/portal#9]
An app allowing 42 Bangkok student to publicly or anonymously create post and reply to post

**Comment by kcp2p** [comment]
https://github.com/orgs/42-Bangkok/discussions/categories/ideas

Issues not related to the current stack should be moved to discussion.

**Comment by hazamashoken** [comment]
move to https://github.com/orgs/42-Bangkok/discussions/11
